packwiz modrinth add --project-id "Gi02250Z" --version-id "cHGan9fQ" --version-filename "Almanac-1.21.1-2-neoforge-1.5.2.jar" -y
packwiz modrinth add --project-id "fM515JnW" --version-id "RZyxhsqY" --version-filename "AmbientSounds_NEOFORGE_v6.3.8_mc1.21.1.jar" -y
packwiz modrinth add --project-id "g96Z4WVZ" --version-id "S2qthD5S" --version-filename "BadOptimizations-2.4.1-1.21.1.jar" -y
packwiz modrinth add --project-id "Q2OqKxDG" --version-id "FjTYILOi" --version-filename "BetterAdvancements-NeoForge-1.21.1-0.4.3.21.jar" -y
packwiz modrinth add --project-id "fALzjamp" --version-id "LuFhm4eU" --version-filename "Chunky-NeoForge-1.4.23.jar" -y
packwiz modrinth add --project-id "Wnxd13zP" --version-id "jo7lDoK4" --version-filename "Clumps-neoforge-1.21.1-19.0.0.1.jar" -y
packwiz modrinth add --project-id "xv94TkTM" --version-id "FaNppCJJ" --version-filename "Controlling-neoforge-1.21.1-19.0.5.jar" -y
packwiz modrinth add --project-id "ix1qq8Ux" --version-id "APbTyOXD" --version-filename "CrashAssistant-neoforge-1.20.6-1.21.4-1.11.9.jar" -y
packwiz modrinth add --project-id "dzb1a5WV" --version-id "r0TIh2nX" --version-filename "CreateDragonsPlus-1.10.1.jar" -y
packwiz modrinth add --project-id "OsZiaDHq" --version-id "vp5wWD4w" --version-filename "CreativeCore_NEOFORGE_v2.13.39_mc1.21.1.jar" -y
packwiz modrinth add --project-id "HSfsxuTo" --version-id "CuBdAr31" --version-filename "Explorify v1.6.5.mod.jar" -y
packwiz modrinth add --project-id "ALTwwcC5" --version-id "VbgSXj57" --version-filename "Falling Leaves-1.0.jar" -y
packwiz modrinth add --project-id "R2OftAxM" --version-id "GbNuOZ4S" --version-filename "FarmersDelight-1.21.1-1.3.2.jar" -y
packwiz modrinth add --project-id "5ZwdcRci" --version-id "PhxY0iHw" --version-filename "ImmediatelyFast-NeoForge-1.6.10+1.21.1.jar" -y
packwiz modrinth add --project-id "O7RBXm3n" --version-id "vjuNnHLv" --version-filename "InventoryProfilesNext-neoforge-1.21.1-2.2.5.jar" -y
packwiz modrinth add --project-id "nvQzSEkH" --version-id "yd8FKCmx" --version-filename "Jade-1.21.1-NeoForge-15.10.5.jar" -y
packwiz modrinth add --project-id "2ecVyZ49" --version-id "kL32PN9Q" --version-filename "Ksyxis-1.4.3.jar" -y
packwiz modrinth add --project-id "46KJle7n" --version-id "RM2acghH" --version-filename "L_Ender's Cataclysm 1.21.1-3.27.jar" -y
packwiz modrinth add --project-id "aC3cM3Vq" --version-id "9I21YYxf" --version-filename "MouseTweaks-neoforge-mc1.21-2.26.1.jar" -y
packwiz modrinth add --project-id "fPetb5Kh" --version-id "nFniEtJV" --version-filename "NaturesCompass-1.21.1-3.4.0-neoforge.jar" -y
packwiz modrinth add --project-id "LPjGiSO4" --version-id "3fv8O3xX" --version-filename "Nullscape_1.21.x_v1.2.14.jar" -y
packwiz modrinth add --project-id "nU0bVIaL" --version-id "BIogJv2D" --version-filename "Patchouli-1.21.1-93-NEOFORGE.jar" -y
packwiz modrinth add --project-id "CU0PAyzb" --version-id "CLZfFbCx" --version-filename "Paxi-1.21.1-NeoForge-5.1.3.jar" -y
packwiz modrinth add --project-id "fuuu3xnx" --version-id "iEE85X0w" --version-filename "Searchables-neoforge-1.21.1-1.0.2.jar" -y
packwiz modrinth add --project-id "6avVoBVB" --version-id "Ic73EcJ6" --version-filename "SimplyTooltips-neoforge-0.1.3.jar" -y
packwiz modrinth add --project-id "PuyPazRT" --version-id "O5EpeqI3" --version-filename "SmartBrainLib-neoforge-1.21.1-1.16.11.jar" -y
packwiz modrinth add --project-id "aKCwCJlY" --version-id "Nvh2sSPX" --version-filename "Structory_26.1_v1.3.16.jar" -y
packwiz modrinth add --project-id "8oi3bsk5" --version-id "MuJMtPGQ" --version-filename "Terralith_1.21.x_v2.5.8.jar" -y
packwiz modrinth add --project-id "Ua7DFN59" --version-id "ZB22DE9q" --version-filename "YungsApi-1.21.1-NeoForge-5.1.6.jar" -y
packwiz modrinth add --project-id "pNabrMMw" --version-id "y9YgjcrO" --version-filename "ae2wtlib-19.5.0.jar" -y
packwiz modrinth add --project-id "r0v8vy1s" --version-id "PCNyL6v4" --version-filename "alternate_current-mc1.21-1.9.0.jar" -y
packwiz modrinth add --project-id "6iTJugQR" --version-id "8xf6Wpxs" --version-filename "amendments-1.21-2.0.15-neoforge.jar" -y
packwiz modrinth add --project-id "EsAfCjCV" --version-id "uAKA6Laj" --version-filename "appleskin-neoforge-mc1.21-3.0.9.jar" -y
packwiz modrinth add --project-id "XxWD5pD3" --version-id "kfyIqgJ6" --version-filename "appliedenergistics2-19.2.17.jar" -y
packwiz modrinth add --project-id "lhGA9TYQ" --version-id "ZxYGwlk0" --version-filename "architectury-13.0.8-neoforge.jar" -y
packwiz modrinth add --project-id "TKB6INcv" --version-id "8VP4YHYr" --version-filename "ars_nouveau-1.21.1-5.11.5.jar" -y
packwiz modrinth add --project-id "b1ZV3DIJ" --version-id "dJgL278E" --version-filename "athena-neoforge-1.21.1-4.0.6.jar" -y
packwiz modrinth add --project-id "MBAkmtvl" --version-id "3XiinKbh" --version-filename "balm-neoforge-1.21.1-21.0.58.jar" -y
packwiz modrinth add --project-id "gJ5afkVv" --version-id "w0mifib8" --version-filename "bellsandwhistles-0.4.7-1.21.1.jar" -y
packwiz modrinth add --project-id "joEfVgkn" --version-id "cgZi7nC7" --version-filename "carryon-neoforge-1.21.1-2.2.4.4.jar" -y
packwiz modrinth add --project-id "BAscRYKm" --version-id "eqVowbGc" --version-filename "chipped-neoforge-1.21.1-4.0.2.jar" -y
packwiz modrinth add --project-id "jJfV67b1" --version-id "uzrkhBpn" --version-filename "citadel-2.7.0-1.21.1.jar" -y
packwiz modrinth add --project-id "9s6osm5g" --version-id "izKINKFg" --version-filename "cloth-config-15.0.140-neoforge.jar" -y
packwiz modrinth add --project-id "UT2M39wf" --version-id "kecZ0sl7" --version-filename "copycats-3.0.4+mc.1.21.1-neoforge.jar" -y
packwiz modrinth add --project-id "LNytGWDc" --version-id "UjX6dr61" --version-filename "create-1.21.1-6.0.10.jar" -y
packwiz modrinth add --project-id "oWaK0Q19" --version-id "YhZLrAFC" --version-filename "create-aeronautics-bundled-1.21.1-1.2.1.jar" -y
packwiz modrinth add --project-id "JWGBpFUP" --version-id "zjSKnkVT" --version-filename "create-enchantment-industry-2.3.1.jar" -y
packwiz modrinth add --project-id "Vg5TIO6d" --version-id "tSy3IGxT" --version-filename "create_connected-1.2.0-mc1.21.1.jar" -y
packwiz modrinth add --project-id "1vXRfEHZ" --version-id "2rAbaFXC" --version-filename "create_mobile_packages-1.21.1-0.7.6.jar" -y
packwiz modrinth add --project-id "9enMEvoc" --version-id "ZFrDlvkl" --version-filename "create_structures_arise-176.49.48 NeoForge 1.21.1.jar" -y
packwiz modrinth add --project-id "hddN8ksR" --version-id "t17qYXjn" --version-filename "create_vibrant_vaults-0.3.2.jar" -y
packwiz modrinth add --project-id "kU1G12Nn" --version-id "3ptU8Nq9" --version-filename "createaddition-1.5.11.jar" -y
packwiz modrinth add --project-id "lMYIHZNH" --version-id "QWqEdWHy" --version-filename "createbetterfps-1.21.1-1.1.4.jar" -y
packwiz modrinth add --project-id "GWp4jCJj" --version-id "bsGaXKEd" --version-filename "createbigcannons-5.11.3+mc.1.21.1.jar" -y
packwiz modrinth add --project-id "sMvUb4Rb" --version-id "qrcMVoBD" --version-filename "createdeco-2.1.3.jar" -y
packwiz modrinth add --project-id "15fFZ3f4" --version-id "1BtGyIVR" --version-filename "createframed-1.21.1-1.7.3.jar" -y
packwiz modrinth add --project-id "ApkoHNO9" --version-id "hTnJ29I0" --version-filename "createpropulsion-1.1.4.jar" -y
packwiz modrinth add --project-id "97LKd1Lf" --version-id "nSe63L2r" --version-filename "createreautomated-1.21.1-neoforge-0.2.0.jar" -y
packwiz modrinth add --project-id "cl223EMc" --version-id "JbGjwnV6" --version-filename "cristellib-neoforge-1.21.1-3.1.5.jar" -y
packwiz modrinth add --project-id "vvuO3ImH" --version-id "yohfFbgD" --version-filename "curios-neoforge-9.5.1+1.21.1.jar" -y
packwiz modrinth add --project-id "LQ3K71Q1" --version-id "T238FZpQ" --version-filename "dynamic-fps-3.11.4+minecraft-1.21.0-neoforge.jar" -y
packwiz modrinth add --project-id "fRiHVvU7" --version-id "5sIPA1To" --version-filename "emi-1.1.24+1.21.1+neoforge.jar" -y
packwiz modrinth add --project-id "NNAgCjsB" --version-id "2tOn8XA2" --version-filename "entityculling-neoforge-1.10.2-mc1.21.1.jar" -y
packwiz modrinth add --project-id "vu3NZ5Ma" --version-id "NQynI1o8" --version-filename "epic-fight-21.17.2-mc1.21.1-neoforge.jar" -y
packwiz modrinth add --project-id "L6jvzao4" --version-id "bdxNv9fy" --version-filename "epic-knights-1.21.1-neoforge-10.12.jar" -y
packwiz modrinth add --project-id "txMuoRai" --version-id "ZLkRGFj6" --version-filename "epic-knights-addon-2.5-1.21.1-neoforge.jar" -y
packwiz modrinth add --project-id "uXXizFIs" --version-id "x7kQWVju" --version-filename "ferritecore-7.0.3-neoforge.jar" -y
packwiz modrinth add --project-id "dCKRaeBC" --version-id "bNQ9lJbg" --version-filename "forgematica-0.4.1+mc1.21.1.jar" -y
packwiz modrinth add --project-id "hYykXjDp" --version-id "MAPG6cXE" --version-filename "fzzy_config-0.7.6+1.21+neoforge.jar" -y
packwiz modrinth add --project-id "8BmcQJ2H" --version-id "gFmrC8Ru" --version-filename "geckolib-neoforge-1.21.1-4.8.4.jar" -y
packwiz modrinth add --project-id "Ck4E7v7R" --version-id "bFr2FBaJ" --version-filename "guideme-21.1.16.jar" -y
packwiz modrinth add --project-id "pJmCFF0p" --version-id "JfqnpP2Z" --version-filename "handcrafted-neoforge-1.21.1-4.0.3.jar" -y
packwiz modrinth add --project-id "YL57xq9U" --version-id "t3ruzodq" --version-filename "iris-neoforge-1.8.12+mc1.21.1.jar" -y
packwiz modrinth add --project-id "yPlaLxD1" --version-id "WZ25JeYB" --version-filename "ironfurnaces-neoforge-1.21.1-4.3.2.jar" -y
packwiz modrinth add --project-id "ordsPcFz" --version-id "NrSebcsG" --version-filename "kotlinforforge-5.11.0-all.jar" -y
packwiz modrinth add --project-id "JkxWVYwU" --version-id "SUeOFygw" --version-filename "krypton_fnp-neoforge-1.21.1-0.2.28.1-1.21.1.jar" -y
packwiz modrinth add --project-id "vE2FN5qn" --version-id "fgcMDg9B" --version-filename "letmedespawn-1.21.x-neoforge-1.5.0.jar" -y
packwiz modrinth add --project-id "onSQdWhM" --version-id "BGe4KMlE" --version-filename "libIPN-neoforge-1.21.1-6.6.3.jar" -y
packwiz modrinth add --project-id "FoVacERa" --version-id "EuxMIyMd" --version-filename "lionfishapi-2.8.jar" -y
packwiz modrinth add --project-id "gvQqBUqZ" --version-id "RXHf27Wv" --version-filename "lithium-neoforge-0.15.3+mc1.21.1.jar" -y
packwiz modrinth add --project-id "SKI34J7B" --version-id "CgDQ0u0Q" --version-filename "mafglib-0.4.3+mc1.21.1.jar" -y
packwiz modrinth add --project-id "nmDcB62a" --version-id "nWk1yGgV" --version-filename "modernfix-neoforge-5.27.11+mc1.21.1.jar" -y
packwiz modrinth add --project-id "692GClaE" --version-id "Uw0AZJKz" --version-filename "modonomicon-1.21.1-neoforge-1.120.1.jar" -y
packwiz modrinth add --project-id "twkfQtEc" --version-id "er7S98Q1" --version-filename "moonlight-neoforge-1.21.1-3.0.14.jar" -y
packwiz modrinth add --project-id "51shyZVL" --version-id "BvOuEhk4" --version-filename "moreculling-neoforge-1.21.1-1.0.7.jar" -y
packwiz modrinth add --project-id "EFw4zpPM" --version-id "XsUAZGlz" --version-filename "new_weapons-1.0.8-neoforge-1.21.1.jar" -y
packwiz modrinth add --project-id "sbJh4AZw" --version-id "8YVnfDm6" --version-filename "occultism-1.21.1-neoforge-1.215.0.jar" -y
packwiz modrinth add --project-id "ik2WZkTZ" --version-id "SZ95SIk8" --version-filename "petrolpark-1.21.1-1.4.35.jar" -y
packwiz modrinth add --project-id "AN0CZD9P" --version-id "PFCZOOlN" --version-filename "petrolsparts-1.21.1-1.2.10.jar" -y
packwiz modrinth add --project-id "tagwiZkJ" --version-id "VEburL70" --version-filename "polymorph-neoforge-1.1.0+1.21.1.jar" -y
packwiz modrinth add --project-id "G1hIVOrD" --version-id "x99nCLTm" --version-filename "resourcefullib-neoforge-1.21-3.0.12.jar" -y
packwiz modrinth add --project-id "X7sDJU5f" --version-id "dCOHonqJ" --version-filename "retrorig_pipes-1.0.1.jar" -y
packwiz modrinth add --project-id "7CAHw34C" --version-id "hwVzI71W" --version-filename "retrorig_quarry-1.3.3.jar" -y
packwiz modrinth add --project-id "B3pb093D" --version-id "hZ6B2Z0x" --version-filename "ritchiesprojectilelib-2.1.2+mc.1.21.1-neoforge.jar" -y
packwiz modrinth add --project-id "T9PomCSv" --version-id "3FMsUjO4" --version-filename "sable-neoforge-1.21.1-1.2.2.jar" -y
packwiz modrinth add --project-id "4WWQxlQP" --version-id "zEViyXZ9" --version-filename "servercore-neoforge-1.5.17+1.21.1.jar" -y
packwiz modrinth add --project-id "2M01OLQq" --version-id "IuqNIoAi" --version-filename "shulkerboxtooltip-neoforge-5.1.9+1.21.1.jar" -y
packwiz modrinth add --project-id "bK3Ubu9p" --version-id "eREhvVpQ" --version-filename "simplyswords-neoforge-1.63.0-1.21.1.jar" -y
packwiz modrinth add --project-id "AANobbMI" --version-id "Pb3OXVqC" --version-filename "sodium-neoforge-0.6.13+mc1.21.1.jar" -y
packwiz modrinth add --project-id "qyVF9oeo" --version-id "cTTunNxQ" --version-filename "sound-physics-remastered-neoforge-1.21.1-1.4.10.jar" -y
packwiz modrinth add --project-id "l6YH9Als" --version-id "v5qtqRQi" --version-filename "spark-1.10.124-neoforge.jar" -y
packwiz modrinth add --project-id "fFEIiSDQ" --version-id "4XwZg5Dq" --version-filename "supplementaries-neoforge-1.21.1-3.6.5.jar" -y
packwiz modrinth add --project-id "DjLobEOy" --version-id "5PS5OhIh" --version-filename "t_and_t-neoforge-fabric-1.13.9+1.21.1.jar" -y
packwiz modrinth add --project-id "USgVjXsk" --version-id "uDi14nbt" --version-filename "tfmg-1.2.0.jar" -y
packwiz modrinth add --project-id "rlloIFEV" --version-id "dkNVC1cq" --version-filename "travelersbackpack-neoforge-1.21.1-10.1.36.jar" -y
packwiz modrinth add --project-id "LOpKHB2A" --version-id "PXntW965" --version-filename "waystones-neoforge-1.21.1-21.1.33.jar" -y
packwiz modrinth add --project-id "1bokaNcj" --version-id "CklXEjmp" --version-filename "xaerominimap-neoforge-1.21.1-25.3.13.jar" -y
packwiz modrinth add --project-id "YJgkgKMm" --version-id "E7slFfkn" --version-filename "xaeros-map-server-utils-1.1.0.jar" -y
packwiz modrinth add --project-id "NcUtCpym" --version-id "XwL25au3" --version-filename "xaeroworldmap-neoforge-1.21.1-1.40.16.jar" -y
