name = "Ephshteyn Island Pack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea6d0dcf0647505604e6624237d3a0336cb1f64c9097feec0aadbeb0875a0aba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
