name = "Ephshteyn Island Pack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba2ca29ec15ba977e17041247f37fbb4b47056670176b71e3605301ff4686097"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
