name = "Ephshteyn Island Pack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4ff860e9add16ee509cd0641dd7a1e32dad5adc99fa83949c899777bc2afc27"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
